### ISSUE TITLE
Localhost querying google.internal addresses dozens of times a second

### ISSUE THREAD

**Issue by dwyeraidan** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#56] opened 2022-03-30 03:09 UTC
Hi there,
Great project thanks! 
I've noticed when the pi-hole admin page is open in browser, there is a spike in localhost requests for the hostnames of the VM instance on google cloud.

See the hostnames in attached screenshot. Mostly "pi-hole.google.internal".  The requests are being served by the cache, but come back as NXDOMAIN.
The total queries starts to go up about a dozen request per second, with no other devices performing lookups.

When I close the browser admin page window , you can see the requests stop. 
[I'm using an iOS App called Pi-hole remote to see a live-log of requests as they come in]

Its like there's an element on the pi-hole admin page itself that is trying to resolve these addresses.

I've set this up fresh as per instructions. Is this known, or even a problem?

cheers

![Screen Shot 2022-03-30 at 13 01 23](https://user-images.githubusercontent.com/77534662/160743014-5580328d-4053-4146-8678-b58e02fdb95f.png)

**Comment by rajannpatel** [comment] 2024-06-20 05:04
Can you confirm this issue is still presenting itself, after following the latest version of this guide?

**Comment by rajannpatel** [comment] 2024-07-26 04:41
I am unable to reproduce this, closing until we have steps or clarity about how to replicate this issue

**Closed by rajannpatel** 2024-07-26 04:41 UTC
